version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: apitickets_mysql
    environment:
      MYSQL_DATABASE: apiticket
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: apipass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_ticket_system.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apitickets_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: .
    container_name: apitickets_api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/apiticket?useSSL=false&serverTimezone=UTC
      DB_USER: apiuser
      DB_PASS: apipass123
      JWT_SECRET: claveSuperSecreta12345678901234567890123456789012345678901234567890
      APP_DEFAULT_PASSWORD: 123456
    networks:
      - apitickets_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  apitickets_network:
    driver: bridge
